### ISSUE TITLE
[BUG] Third-party JDBC drivers and java.sql.driver

### ISSUE THREAD

**Issue by ADevaux42** [nextgenhealthcare/connect#4719]
**Describe the bug**
When I try to use a third-party jar file for a JDBC driver, through a database source connector, I get the following error:

```
Caused by: java.lang.ClassNotFoundException: java.sql.Driver
at java.base/java.net.URLClassLoader.findClass(Unknown Source)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
```

It is showed whenever I try to get tables list or to deploy a channel using it.

Those same third-party jar files are used with Mirth 3.7.1 (on Windows) without any problem, but we're trying to switch into a Docker infrastructure.

**To Reproduce**
This can be reproduced even with the postgresql jdbc driver coming with Mirth.
Setup steps for Postgresql (here it's *postgresql-42.2.19.jar* coming with the Docker image) :
1. Configure docker-compose with a repo for the JDBC drivers that you'll map on the container (in my docker-compose below: /storage/mirth/custom-lib:/opt/connect/extra-db-lib);
2. In this repo, you can copy the *postgresql-42.2.19.jar* file;
3. Start your container, ensure it works;
4. Go to "Settings" > "Resources" tab > click "Add Resource" and setup the directory with the jar file and save.

1. Create a new channel, go to source and select "Database reader";
2. Select Driver "PostgreSQL";
3. You can insert the URL template (without changing it);
4. Enter dummy user and password (the exception comes before it can perform any check over url, user of password)
5. Click the "Select" button and then click "Get Tables"
6. See error

**Expected behavior**
Mirth should be able to connect a database with a third party JDBC driver library using java.sql.driver.

**Actual behavior**
A JAVA exception is thrown invoking ClassNotFoundException for java.sql.driver and then, the driver is not usable.

**Screenshots**
![image](https://user-images.githubusercontent.com/3499321/132172649-e94f0436-0b11-4320-af51-6cfec75c9244.png)

![image](https://user-images.githubusercontent.com/3499321/132172689-1da56273-8dc5-42c5-a6b9-8a83bce1d9b9.png)

![image](https://user-images.githubusercontent.com/3499321/132172706-3d50213d-ffd8-4863-bfb9-58d6b81862d3.png)

**Environment:**
 - OS: Alpine Linux running Docker
 - Docker image : nextgenhealthcare/connect:3.11.0
 - Java Distribution/Version: OpenJDK 11
 - Connect Version 3.11.0

**Workaround(s)**
Are there one or more workarounds for this issue currently? None

**Additional context**
- Here is my compose file:
```yaml
version: "3.8"
services:
  mirth_3_11:
    image: nextgenhealthcare/connect:3.11.0
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://XXXXXX:5432/mirth_3_11
      - DATABASE_MAX_CONNECTIONS=50
      - DATABASE_USERNAME=XXXX
      - DATABASE_PASSWORD=XXXX
      - _MP_HTTPS_SERVER_PROTOCOLS='TLSv1.3,TLSv1.2'
    volumes:
      - /storage/mirth/custom-lib:/opt/connect/extra-db-lib # folder for the JDBC libraries for third-party drivers (AS400, Cache)
      - /storage/mirth/mcserver_base.vmoptions:/opt/connect/mcserver_base.vmoptions
      - /storage/mirth/appdata:/opt/connect/appdata
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      #- 8080:8080/tcp
      - 8443:8443/tcp
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == XXXXXXX]
```
- Here is my mcserver_base.vmoptions with specific elements required due to JAVA9+ options/modules:
(As you can see, I explicitely ask the vm to add module "java.sql" that should contain java.sql.driver.
```
-server
-Xmx768m
-Djava.awt.headless=true
-Dapple.awt.UIElement=true
--add-modules=java.sql,java.sql.rowset
--add-exports=java.base/com.sun.crypto.provider=ALL-UNNAMED
--add-exports=java.base/sun.security.provider=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.math=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/java.security=ALL-UNNAMED
--add-opens=java.base/java.security.cert=ALL-UNNAMED
--add-opens=java.base/java.text=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/sun.security.pkcs=ALL-UNNAMED
--add-opens=java.base/sun.security.rsa=ALL-UNNAMED
--add-opens=java.base/sun.security.x509=ALL-UNNAMED
--add-opens=java.desktop/java.awt=ALL-UNNAMED
--add-opens=java.desktop/java.awt.color=ALL-UNNAMED
--add-opens=java.desktop/java.awt.font=ALL-UNNAMED
--add-opens=java.xml/com.sun.org.apache.xalan.internal.xsltc.trax=ALL-UNNAMED
```

- I've checked a lot of things, including that OpeJDK has the module (and it has), and I finished to found nothing but those 2 references (for jetbrains) that seems quite similar and may help you ?
   - https://youtrack.jetbrains.com/issue/IDEA-211257
   - https://youtrack.jetbrains.com/issue/IDEA-226574

It's really a great tool, but it's locking us since we cannot upgrade all our channels.

Thank you already for the help!
Alexandre
